### ISSUE TITLE
bls changed API to 2.3 (2/28/2018)

### ISSUE THREAD

**Issue by pgg1309** [mikeasilva/blsAPI#17]
Mike, 
BLS has changed its API and now returns an extra field 'latest' (true or false). 
This breaks down your function. In order to make it work again all that is needed is to add 
      d$latest <- NULL
after the code:
        d$footnotes <- NULL
But I'm not familiar enough with GitHub to make that change myself.

**Comment by mikeasilva** [comment]
@pgg1309 Thanks for the feedback.  I have merged in your change.

**Comment by zmokhiber** [comment]
I believe there is a  discrepancy between the CRAN version and the github version of the package.
In version posted here this is correctly implemented. 
```r
d$footnotes <- NULL
d$latest <- NULL
```
However, the CRAN version still only has:
```r
d$footnotes <- NULL
```
Which means the `latest` field still appears when running the CRAN version of the package.

Downloading the github version will remove the extra fields as intended. 
```r
library(devtools)
install_github('mikeasilva/blsAPI')
```
Note that the arguments are named with underscores instead of periods in the github version, which can cause an error if argument names in the `blsAPI` function are spelled out in your code.
